### PR TITLE
Added reverse function to reversibly parse Bangla typed text to English-typed Bangla text.

### PR DESCRIPTION
**Pull request by TanimSk**
Changes made:

- Modified dictionary according to the suggestions made by the participants in the GitHub discussion
- Modified main.py for reverse function
- Modified Readme file a bit
- Added tests

(consider it as an experimental release for reverse function )

### CODE REVIEW

**Review by hitblast — APPROVED** [review]
Banger PR! I'll merge once I'm done with the checks.

**Comment by hitblast** [comment]
@TanimSk Oh looks like both of the checks have failed. Could you have a look at it?

**Comment by TanimSk** [comment]
my bad, checking it
updating ASAP

**Comment by hitblast** [comment]
Thanks! Merging.

**Pull request merged**
